ingress: "https://arbeidsplassen.nav.no/min-side"
arbeidsplassen_url: "https://arbeidsplassen.nav.no"
loglevel: "debug"
namespace: "teampam"
pam_aduser_audience: "prod-gcp:teampam:pam-aduser"
pam_aduser_url: "http://pam-aduser"
amplitude_token: "a7b3f00008ae250a08c3ebbc6bf718f9"
