name: deploy-prod
on:
  release:
    types: [ published ]

jobs:
  deploy-prod:
    permissions:
      contents: write
    uses: navikt/pam-deploy/.github/workflows/deploy-prod.yml@v5
    with:
      NAIS_RESOURCE: .nais/nais.yml
      NAIS_VARS: .nais/prod.yml
    secrets:
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
